
import java.util.HashSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482321033
 */
public class formCategorias extends javax.swing.JFrame {

    /**
     * Creates new form Formularios
     */
    public formCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeCategoriasTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descricaoCategoriasTF = new javax.swing.JTextField();
        salvarCategorias = new javax.swing.JButton();
        atualizarCategorias = new javax.swing.JButton();
        consultarCategorias = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        excluirCategorias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Categorias");

        jLabel3.setText("Nome");

        jLabel4.setText("Descrição");

        descricaoCategoriasTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoCategoriasTFActionPerformed(evt);
            }
        });

        salvarCategorias.setText("Inserir");
        salvarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCategoriasActionPerformed(evt);
            }
        });

        atualizarCategorias.setText("Atualizar");
        atualizarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCategoriasActionPerformed(evt);
            }
        });

        consultarCategorias.setText("Consultar");
        consultarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCategoriasActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        excluirCategorias.setText("Excluir");
        excluirCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(descricaoCategoriasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCategoriasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(consultarCategorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarCategorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirCategorias))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salvarCategorias))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeCategoriasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricaoCategoriasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(salvarCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarCategorias)
                    .addComponent(atualizarCategorias)
                    .addComponent(excluirCategorias))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoCategoriasTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoCategoriasTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoCategoriasTFActionPerformed

    private void salvarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCategoriasActionPerformed
        // TODO add your handling code here:
        Categorias cat = new Categorias();
        cat.setNome(nomeCategoriasTF.getText());
        cat.setDescricao(descricaoCategoriasTF.getText());
        
        CategoriasDAO catDAO = new CategoriasDAO();
        catDAO.inserir(cat);
        JOptionPane.showMessageDialog(this, "Categoria inserida com sucesso!");
        limparFormularioCategorias();
    }//GEN-LAST:event_salvarCategoriasActionPerformed

    private void atualizarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCategoriasActionPerformed
        // TODO add your handling code here:
       if (idTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, consulte uma categoria antes de atualizar.");
            return;
        }
        Categorias cat = new Categorias();
        cat.setCatId(Integer.parseInt(idTextField.getText()));
        cat.setNome(nomeCategoriasTF.getText());
        cat.setDescricao(descricaoCategoriasTF.getText());

        CategoriasDAO catDAO = new CategoriasDAO();
        catDAO.editar(cat);
        JOptionPane.showMessageDialog(this, "Categoria atualizada com sucesso!");
        limparFormularioCategorias();                 
    }//GEN-LAST:event_atualizarCategoriasActionPerformed

    private void consultarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCategoriasActionPerformed
        // TODO add your handling code here:
          if (idTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe um ID para consultar.");
            return;
        }
        int catId = Integer.parseInt(idTextField.getText());
        CategoriasDAO catDAO = new CategoriasDAO();
        Categorias cat = catDAO.getCategorias(catId);
        if (cat == null) {
            JOptionPane.showMessageDialog(this, "Categoria não encontrada!");
            limparFormularioCategorias();
        } else {
            nomeCategoriasTF.setText(cat.getNome());
            descricaoCategoriasTF.setText(cat.getDescricao());
        }
  
    }//GEN-LAST:event_consultarCategoriasActionPerformed

    private void excluirCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCategoriasActionPerformed
        // TODO add your handling code here:
         if (idTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe um ID para excluir.");
            return;
        }

        // Adiciona uma caixa de diálogo para confirmação
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esta categoria?", "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            int catId = Integer.parseInt(idTextField.getText());
            CategoriasDAO catDAO = new CategoriasDAO();
            catDAO.excluir(catId);
            JOptionPane.showMessageDialog(this, "Categoria excluída com sucesso!");
            limparFormularioCategorias();
        }
    }//GEN-LAST:event_excluirCategoriasActionPerformed
  public void limparFormularioCategorias(){
         idTextField.setText("");
         nomeCategoriasTF.setText("");
         descricaoCategoriasTF.setText(""); 
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarCategorias;
    private javax.swing.JButton consultarCategorias;
    private javax.swing.JTextField descricaoCategoriasTF;
    private javax.swing.JButton excluirCategorias;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCategoriasTF;
    private javax.swing.JButton salvarCategorias;
    // End of variables declaration//GEN-END:variables
}
