
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thiag
 */
public class formProdutos extends javax.swing.JFrame {

    /**
     * Creates new form formProdutos
     */
    public formProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeProdutoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descricaoProdutoTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        precoCustoTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        precoVendaTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        estoqueTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idCategoriaTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idProdutoTF = new javax.swing.JTextField();
        inserirProdutoBtn = new javax.swing.JButton();
        consultarProdutoBtn = new javax.swing.JButton();
        atualizarProdutoBtn = new javax.swing.JButton();
        excluirProdutoBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        codigoBarrasTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Produtos");

        jLabel2.setText("Nome");

        nomeProdutoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoTFActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição");

        jLabel4.setText("Preço Custo");

        jLabel5.setText("Preço Venda");

        jLabel6.setText("Estoque");

        jLabel7.setText("Id Categorias");

        jLabel8.setText("ID");

        inserirProdutoBtn.setText("Inserir");
        inserirProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirProdutoBtnActionPerformed(evt);
            }
        });

        consultarProdutoBtn.setText("Consulta");
        consultarProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProdutoBtnActionPerformed(evt);
            }
        });

        atualizarProdutoBtn.setText("Atualizar");
        atualizarProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarProdutoBtnActionPerformed(evt);
            }
        });

        excluirProdutoBtn.setText("Excluir");
        excluirProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdutoBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Código de Barras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCategoriaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(inserirProdutoBtn)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(codigoBarrasTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(estoqueTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoVendaTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoCustoTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoProdutoTA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeProdutoTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idProdutoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluirProdutoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarProdutoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarProdutoBtn)))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(idProdutoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarProdutoBtn)
                    .addComponent(atualizarProdutoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProdutoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirProdutoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricaoProdutoTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precoCustoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precoVendaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estoqueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigoBarrasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idCategoriaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inserirProdutoBtn)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeProdutoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoTFActionPerformed

    private void inserirProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirProdutoBtnActionPerformed
        // TODO add your handling code here:
        try {
            Produtos produto = new Produtos();
            produto.setNome(nomeProdutoTF.getText());
            produto.setDescricao(descricaoProdutoTA.getText());
            produto.setPrecoCusto(new BigDecimal(precoCustoTF.getText()));
            produto.setPrecoVenda(new BigDecimal(precoVendaTF.getText()));
            produto.setQuantidadeEstoque(Integer.parseInt(estoqueTF.getText()));
            produto.setCodigoBarras(codigoBarrasTF.getText());
            produto.setIdCategoria(Integer.parseInt(idCategoriaTF.getText()));
    
            ProdutosDAO produtoDAO = new ProdutosDAO();
            produtoDAO.inserir(produto);
            
            JOptionPane.showMessageDialog(this, "Produto inserido com sucesso!");
            limparFormulario();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro de formato numérico: Verifique os campos de preço, estoque e ID da categoria.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inserirProdutoBtnActionPerformed

    private void consultarProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProdutoBtnActionPerformed
        // TODO add your handling code here:
        
        if (idProdutoTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe um ID para consultar.");
            return;
        }

        try {
            int id = Integer.parseInt(idProdutoTF.getText());
            ProdutosDAO produtoDAO = new ProdutosDAO();
            Produtos produto = produtoDAO.getProduto(id);
    
            if (produto == null) {
                JOptionPane.showMessageDialog(this, "Produto não encontrado.");
                limparFormulario();
            } else {
                nomeProdutoTF.setText(produto.getNome());
                descricaoProdutoTA.setText(produto.getDescricao());
                precoCustoTF.setText(produto.getPrecoCusto() != null ? produto.getPrecoCusto().toString() : "");
                precoVendaTF.setText(produto.getPrecoVenda() != null ? produto.getPrecoVenda().toString() : "");
                estoqueTF.setText(String.valueOf(produto.getQuantidadeEstoque()));
                codigoBarrasTF.setText(produto.getCodigoBarras()); 
                idCategoriaTF.setText(String.valueOf(produto.getIdCategoria()));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O ID deve ser um número válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultarProdutoBtnActionPerformed

    private void atualizarProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarProdutoBtnActionPerformed
        // TODO add your handling code here:
        if (idProdutoTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Consulte um produto antes de atualizar.");
            return;
        }

        try {
            Produtos produto = new Produtos();
            produto.setIdProduto(Integer.parseInt(idProdutoTF.getText()));
            produto.setNome(nomeProdutoTF.getText());
            produto.setDescricao(descricaoProdutoTA.getText());
            produto.setPrecoCusto(new BigDecimal(precoCustoTF.getText()));
            produto.setPrecoVenda(new BigDecimal(precoVendaTF.getText()));
            produto.setQuantidadeEstoque(Integer.parseInt(estoqueTF.getText()));
            produto.setCodigoBarras(codigoBarrasTF.getText()); 
            produto.setIdCategoria(Integer.parseInt(idCategoriaTF.getText()));
    
            ProdutosDAO produtoDAO = new ProdutosDAO();
            produtoDAO.editar(produto);
            
            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");
            limparFormulario();
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Erro de formato numérico ao atualizar.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_atualizarProdutoBtnActionPerformed

    private void excluirProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdutoBtnActionPerformed
        // TODO add your handling code here:
        if (idProdutoTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Consulte um produto antes de excluir.");
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este produto?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(idProdutoTF.getText());
            ProdutosDAO produtoDAO = new ProdutosDAO();
            produtoDAO.excluir(id);
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
            limparFormulario();
        }
    }//GEN-LAST:event_excluirProdutoBtnActionPerformed

     private void limparFormulario() {
        idProdutoTF.setText("");
        nomeProdutoTF.setText("");
        descricaoProdutoTA.setText("");
        precoCustoTF.setText("");
        precoVendaTF.setText("");
        estoqueTF.setText("");
        codigoBarrasTF.setText(""); 
        idCategoriaTF.setText("");
        nomeProdutoTF.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarProdutoBtn;
    private javax.swing.JTextField codigoBarrasTF;
    private javax.swing.JButton consultarProdutoBtn;
    private javax.swing.JTextField descricaoProdutoTA;
    private javax.swing.JTextField estoqueTF;
    private javax.swing.JButton excluirProdutoBtn;
    private javax.swing.JTextField idCategoriaTF;
    private javax.swing.JTextField idProdutoTF;
    private javax.swing.JButton inserirProdutoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeProdutoTF;
    private javax.swing.JTextField precoCustoTF;
    private javax.swing.JTextField precoVendaTF;
    // End of variables declaration//GEN-END:variables
}
