
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thiag
 */
public class formFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form formFornecedores
     */
    public formFornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeEmpresaTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomeContatoTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cnpjTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefoneTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enderecoTF = new javax.swing.JTextField();
        inserirFornecedorBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        idFornecedorTF = new javax.swing.JTextField();
        consultarFornecedorBtn = new javax.swing.JButton();
        atualizarFornecedorBtn = new javax.swing.JButton();
        excluirFornecedorBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fornecedores");

        jLabel2.setText("Nome da Empresa");

        jLabel3.setText("Nome do Contato");

        jLabel4.setText("CNPJ");

        jLabel5.setText("Telefone");

        jLabel6.setText("Email");

        jLabel7.setText("Endereço");

        inserirFornecedorBtn.setText("Inserir");
        inserirFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirFornecedorBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("ID");

        consultarFornecedorBtn.setText("Consultar");
        consultarFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFornecedorBtnActionPerformed(evt);
            }
        });

        atualizarFornecedorBtn.setText("Atualizar");
        atualizarFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarFornecedorBtnActionPerformed(evt);
            }
        });

        excluirFornecedorBtn.setText("Excluir");
        excluirFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFornecedorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(nomeEmpresaTF)
                            .addComponent(jLabel3)
                            .addComponent(nomeContatoTF)
                            .addComponent(jLabel4)
                            .addComponent(cnpjTF)
                            .addComponent(jLabel5)
                            .addComponent(telefoneTF)
                            .addComponent(jLabel6)
                            .addComponent(emailTF)
                            .addComponent(jLabel7)
                            .addComponent(enderecoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idFornecedorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluirFornecedorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarFornecedorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarFornecedorBtn))
                    .addComponent(inserirFornecedorBtn))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(idFornecedorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultarFornecedorBtn)
                            .addComponent(atualizarFornecedorBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeEmpresaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(excluirFornecedorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeContatoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cnpjTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enderecoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inserirFornecedorBtn)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirFornecedorBtnActionPerformed
        Fornecedores fornecedor = new Fornecedores();
        fornecedor.setNomeEmpresa(nomeEmpresaTF.getText());
        fornecedor.setNomeContato(nomeContatoTF.getText());
        fornecedor.setCnpj(cnpjTF.getText());
        fornecedor.setTelefone(telefoneTF.getText());
        fornecedor.setEmail(emailTF.getText());
        fornecedor.setEndereco(enderecoTF.getText());

        FornecedoresDAO fornecedorDAO = new FornecedoresDAO();
        fornecedorDAO.inserir(fornecedor);
        
        JOptionPane.showMessageDialog(this, "Fornecedor inserido com sucesso!");
        limparFormulario();
    }//GEN-LAST:event_inserirFornecedorBtnActionPerformed

    private void consultarFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFornecedorBtnActionPerformed
        // TODO add your handling code here:
        
        if (idFornecedorTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe um ID para consultar.");
            return;
        }

        try {
            int id = Integer.parseInt(idFornecedorTF.getText());
            FornecedoresDAO fornecedorDAO = new FornecedoresDAO();
            Fornecedores fornecedor = fornecedorDAO.getFornecedor(id);
    
            if (fornecedor == null) {
                JOptionPane.showMessageDialog(this, "Fornecedor não encontrado.");
                limparFormulario();
            } else {
                nomeEmpresaTF.setText(fornecedor.getNomeEmpresa());
                nomeContatoTF.setText(fornecedor.getNomeContato());
                cnpjTF.setText(fornecedor.getCnpj());
                telefoneTF.setText(fornecedor.getTelefone());
                emailTF.setText(fornecedor.getEmail());
                enderecoTF.setText(fornecedor.getEndereco());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O ID deve ser um número válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultarFornecedorBtnActionPerformed

    private void atualizarFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarFornecedorBtnActionPerformed
        // TODO add your handling code here:
        
        if (idFornecedorTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Consulte um fornecedor antes de atualizar.");
            return;
        }

        Fornecedores fornecedor = new Fornecedores();
        fornecedor.setIdFornecedor(Integer.parseInt(idFornecedorTF.getText()));
        fornecedor.setNomeEmpresa(nomeEmpresaTF.getText());
        fornecedor.setNomeContato(nomeContatoTF.getText());
        fornecedor.setCnpj(cnpjTF.getText());
        fornecedor.setTelefone(telefoneTF.getText());
        fornecedor.setEmail(emailTF.getText());
        fornecedor.setEndereco(enderecoTF.getText());

        FornecedoresDAO fornecedorDAO = new FornecedoresDAO();
        fornecedorDAO.editar(fornecedor);
        
        JOptionPane.showMessageDialog(this, "Fornecedor atualizado com sucesso!");
        limparFormulario();
        
    }//GEN-LAST:event_atualizarFornecedorBtnActionPerformed

    private void excluirFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFornecedorBtnActionPerformed
        // TODO add your handling code here:
        
        if (idFornecedorTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Consulte um fornecedor antes de excluir.");
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este fornecedor?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(idFornecedorTF.getText());
            FornecedoresDAO fornecedorDAO = new FornecedoresDAO();
            fornecedorDAO.excluir(id);
            JOptionPane.showMessageDialog(this, "Fornecedor excluído com sucesso!");
            limparFormulario();
        }
        
    }//GEN-LAST:event_excluirFornecedorBtnActionPerformed

    private void limparFormulario() {
        idFornecedorTF.setText("");
        nomeEmpresaTF.setText("");
        nomeContatoTF.setText("");
        cnpjTF.setText("");
        telefoneTF.setText("");
        emailTF.setText("");
        enderecoTF.setText("");
        nomeEmpresaTF.requestFocus();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarFornecedorBtn;
    private javax.swing.JTextField cnpjTF;
    private javax.swing.JButton consultarFornecedorBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField enderecoTF;
    private javax.swing.JButton excluirFornecedorBtn;
    private javax.swing.JTextField idFornecedorTF;
    private javax.swing.JButton inserirFornecedorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeContatoTF;
    private javax.swing.JTextField nomeEmpresaTF;
    private javax.swing.JTextField telefoneTF;
    // End of variables declaration//GEN-END:variables
}
